name: Cypress API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Teste do Projeto
        uses: actions/checkout@v2

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependecies
        run: npm install

      - name: Run cypress test
        run: npx cypress run --headless
