name: Pipeline
on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checlout code
        uses: actions/checkout@v2
      - name: Build
        run: | 
          # Comandos para compilar o código
          
test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: | 
        # Comandos para executar os testes
        
steps:
  - name: Build
    uses: meu-usuario/meu-app-action@v1
