name: Teste do Robot Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Instalar o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar as dependências
      run: pip install robotframework-requests

    - name: Executar os testes do Robot Framework
      run: robot tests/

